"""
Django settings for biblioteca project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# En desarrollo valen los valores de abajo. En el servidor, cada uno se toma de
# una variable de entorno: la clave secreta no puede quedar publicada en el repo
# y DEBUG encendido en produccion filtra el codigo fuente en cada error.

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-6cpzk*miyoek3_=gp$(1$kse1rm2o!f7b#)2w(z&pca61tjn(^',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Vercel publica el dominio del despliegue en VERCEL_URL, sin el esquema.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app']

CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libros',
    'prestamos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estaticos desde la propia app. Sin esto el
    # admin se ve sin estilos en el servidor, porque alli no corre runserver.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biblioteca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biblioteca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Sin DATABASE_URL se usa SQLite, que es lo comodo para desarrollar y para correr
# los tests. En el servidor hay que definirla: un despliegue serverless no tiene
# disco donde escribir, asi que un archivo .sqlite3 no sirve alli.

DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,          # sin conexiones persistentes: cada invocacion es efimera
            ssl_require=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde collectstatic junta los estaticos antes de desplegar.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Microservicio externo de reseñas
# Servicio propio (FastAPI + Supabase) desplegado en Render. Django no accede a
# esa base de datos: la consume por HTTP. En local se levanta en el puerto 8001.

MICROSERVICIO_RESENAS_URL = os.environ.get(
    'MICROSERVICIO_RESENAS_URL',
    'http://127.0.0.1:8001',
).rstrip('/')

MICROSERVICIO_RESENAS_TIMEOUT = 5  # segundos
