"""
Django settings for biblioteca project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# En desarrollo valen los valores de abajo. En el servidor, cada uno se toma de
# una variable de entorno: la clave secreta no puede quedar publicada en el repo
# y DEBUG encendido en produccion filtra el codigo fuente en cada error.

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-6cpzk*miyoek3_=gp$(1$kse1rm2o!f7b#)2w(z&pca61tjn(^',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Vercel publica el dominio del despliegue en VERCEL_URL, sin el esquema.
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.vercel.app']

CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libros',
    'prestamos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los archivos estaticos desde la propia app. Sin esto el
    # admin se ve sin estilos en el servidor, porque alli no corre runserver.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'biblioteca.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'biblioteca.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Sin DATABASE_URL se usa SQLite, que es lo comodo para desarrollar y para correr
# los tests. En el servidor hay que definirla: un despliegue serverless no tiene
# disco donde escribir, asi que un archivo .sqlite3 no sirve alli.

DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0,          # sin conexiones persistentes: cada invocacion es efimera
            ssl_require=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Carpeta donde collectstatic junta los estaticos antes de desplegar.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Microservicio externo de reseñas
# Servicio propio (FastAPI + Supabase) desplegado en Render. Django no accede a
# esa base de datos: la consume por HTTP. En local se levanta en el puerto 8001.

# El sitio y la API comparten dominio y despliegue: el sitio vive en / y la API
# en /api. Vercel publica el dominio del despliegue en VERCEL_URL, asi que no
# hace falta configurar nada. En local, la API se levanta en el puerto 8001.

def _url_del_microservicio():
    explicita = os.environ.get('MICROSERVICIO_RESENAS_URL')
    if explicita:
        return explicita
    # VERCEL_PROJECT_PRODUCTION_URL es el dominio publico y estable del proyecto.
    # VERCEL_URL apunta al deployment concreto, que puede estar detras de la
    # proteccion de acceso: pedirle JSON devuelve la pagina de login.
    dominio = (
        os.environ.get('VERCEL_PROJECT_PRODUCTION_URL')
        or os.environ.get('VERCEL_URL')
    )
    if dominio:
        return f'https://{dominio}/api'
    return 'http://127.0.0.1:8001/api'


MICROSERVICIO_RESENAS_URL = _url_del_microservicio().rstrip('/')

# URL de respaldo para la lectura de reseñas. Es la pieza que da resiliencia:
# si el microservicio primario (Python/FastAPI) no responde, el sitio intenta
# este. Tiene que ser un microservicio escrito en un lenguaje DISTINTO de Python
# (en el repo, NodeJS en el puerto 8002), para que no caiga por el mismo motivo
# que el primario. En local se levanta aparte; en el servidor se define con la
# URL del servicio desplegado.
MICROSERVICIO_RESENAS_FALLBACK_URL = os.environ.get(
    'MICROSERVICIO_RESENAS_FALLBACK_URL',
    'http://127.0.0.1:8002/api',
).rstrip('/')

MICROSERVICIO_RESENAS_TIMEOUT = 5  # segundos


# Microservicios de libros por lenguaje.
# El CRUD de libros (agregar, editar, eliminar) no lo hace el ORM: lo hacen
# microservicios escritos en 4 lenguajes distintos (Python, NodeJS, Java y PHP),
# todos contra la misma tabla `libros` de Supabase. El usuario elige con cuál
# se ejecuta cada operación desde la interfaz (botones), y la elección queda
# guardada en el navegador. Cada URL es sobreescribible por variable de entorno;
# los puertos en local son 8001 (Python), 8002 (NodeJS), 8003 (Java), 8004 (PHP).

def _url_microservicio_libros(nombre, puerto):
    return os.environ.get(
        f'MICROSERVICIO_LIBROS_{nombre.upper()}_URL',
        f'http://127.0.0.1:{puerto}/api',
    ).rstrip('/')


MICROSERVICIOS_LIBROS = {
    'python': _url_microservicio_libros('python', 8001),
    'nodejs': _url_microservicio_libros('nodejs', 8002),
    'java': _url_microservicio_libros('java', 8003),
    'php': _url_microservicio_libros('php', 8004),
}

# Orden en el que se prueban los servicios al LEER libros. El primero es el
# primario; si falla, el sitio cae a los siguientes sin que el usuario se entere.
MICROSERVICIOS_LIBROS_ORDEN_LECTURA = [
    'python',
    'nodejs',
    'java',
    'php',
]


# Asistente con IA
# La clave de la API vive en biblioteca/.env, que settings lee solo. Si la
# variable de entorno ya está definida (por ejemplo en Vercel), gana esa y el
# archivo no hace falta. Sin clave, la vista del asistente degrada con un aviso.

def _leer_env_local():
    """Lee las variables del .env de esta carpeta y las devuelve en un dict."""
    ruta = Path(__file__).resolve().parent / '.env'
    variables = {}
    if not ruta.exists():
        return variables
    for linea in ruta.read_text(encoding='utf-8').splitlines():
        linea = linea.strip()
        if not linea or linea.startswith('#') or '=' not in linea:
            continue
        nombre, _, valor = linea.partition('=')
        variables[nombre.strip()] = valor.strip().strip("'\"")
    return variables


_ENV_LOCAL = _leer_env_local()

IA_API_KEY = os.environ.get('IA_API_KEY') or _ENV_LOCAL.get('IA_API_KEY', '')
IA_API_URL = os.environ.get('IA_API_URL') or _ENV_LOCAL.get(
    'IA_API_URL', 'https://generativelanguage.googleapis.com/v1beta',
)
IA_MODEL = os.environ.get('IA_MODEL') or _ENV_LOCAL.get('IA_MODEL', 'gemini-2.5-flash')
# Sesión que pide el gateway de opencode-go para enrutar. Solo se usa con ese proveedor.
IA_API_SESION = os.environ.get('IA_API_SESION') or _ENV_LOCAL.get('IA_API_SESION', '')
IA_TIMEOUT = 15  # segundos: una consulta de IA tarda más que el microservicio
